// export const BASE_URL = 'http://localhost:3500/';
export const BASE_URL = 'https://final-task-backend-production-fef2.up.railway.app/';
// export const BASE_URL = 'https://final-task-backend-production.onrender.com/';
export const AUTH_SIGNUP = 'auth/signup';
export const AUTH_SIGNIN = 'auth/signin';
export const USERS = 'users/';
export const BOARDS = 'boards/';
export const COLUMNS = 'columns/';
export const TASKS = 'tasks/';
export const TASKS_SET = 'tasksSet/';
export const SEARCH = 'tasksSet?search=';
export const IDS_LIST = 'tasksSet?ids=';
